### ISSUE TITLE
Presto can't be reached

### ISSUE THREAD

**Issue by mohsen74** [wix/quix#116]
I'm using presto v 0.221. I want to connect to presto in my localhost but I get "presto can't be reached" when I query.
I change PRESTO_API in .env file to http://localhost:8080/

**Comment by frolovv** [comment]
@mohsen74 try setting PRESTO_API to `http://localhost:8080/v1`

**Comment by mohsen74** [comment]
i did and the same error.
"Presto can't be reached, please try later. Underlying exception name is ConnectException"

**Comment by antonpod** [comment]
@mohsen74 if you're using the Docker v18.03 and above and you're **not** on Linux, please try to use `http://host.docker.internal:8080/v1`

**Comment by mohsen74** [comment]
Oops, it was my mistake. I am using Linux but I should use my internal IP, not 'localhost' because it is running from docker.
thanks.

**Comment by antonpod** [comment]
Happy to hear it worked out for you :)
Keep us posted if you have any more questions.
