### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by 94ri3** [wix/quix#121]
I run quix on my local presto fine and I can see my MongoDB in explorer too.
but when I try to query I get 'Connection lost' error.
I also can query on my presto with presto Command Line Interface.
this is part of quix log:
`splitsscheduledperiteration.fifteenminutes.p50, splitsscheduledperiteration.fifteenminutes.p75, splitsscheduledperiteration.fiveminutes.count, splitsscheduledperiteration.oneminute.maxerror, splitsscheduledperiteration.oneminute.min, splitsscheduledperiteration.oneminute.total, waitingforsource.fiveminute.rate, level3time, selectedcountlevel0.fiveminute.rate, selectedcountlevel4.fiveminute.rate, authenticationfail.oneminute.rate, utmcampaign, query, analysis_time_ms, literal_suffix, num_prec_radix, class_name, length, table_schem, task_id))]
backend_1   | 2019-06-30 09:02:52,003 DEBUG [qtp1084513659-23]        o.s.web.servlet.DispatcherServlet : Completed 200 OK
`
I've already checked https://github.com/wix/quix/issues/46 but did not work for me

**Comment by frolovv** [comment]
@94ri3 tnx for reporting! 

can you please paste a bit more of the backend log? i can't identify the issue from above lines

**Comment by 94ri3** [comment]
![Screenshot from 2019-07-01 13-14-14](https://user-images.githubusercontent.com/52371785/60422891-32f07d80-9c02-11e9-9c0a-6d52c549c47a.png)

I changed presto port from 8080 to 8181 and it worked once. but get the same error after reboot.
`WebSocket connection to 'ws://localhost:8081/api/v1/execute/sql' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ app.bundle.min.js:1
`
and this is chrom's consol log.
`PRESTO_API=http://185.208.174.194:8080/v1
AUTH_COOKIE=
AUTH_SECRET=
DB_VOLUME_PATH=/var/lib/mysql
AUTH_TYPE=fake
DB_NAME=quix
`
and this is my .env file

thanks for your respond

**Comment by antonpod** [comment]
@94ri3 please see if this is related to your problem https://github.com/wix/quix/issues/116

**Comment by antonpod** [comment]
Scratch that, I see you're providing the IP of your machine and not localhost: PRESTO_API=http://185.208.174.194:8080/v1

**Comment by frolovv** [comment]
it sounds like `quix-backend` knows about presto and can calculate the db tree correctly.

`quix-frontend` knows about `quix-backend` as it fetches db tree correctly
but the UI doesn't know about `quix-backend` and websocket is failing to open.

@sthuck please assist

@94ri3 what are the values of `BACKEND_PUBLIC_URL` and `BACKEND_INTERNAL_URL` in .env file if they exist

**Comment by 94ri3** [comment]
it doesn't exist

**Comment by sthuck** [comment]
Like @frolovv wrote, sounds like the UI (browser) can't reach the backend. 

Assuming you used the default `docker-compose.yaml` we have in our repo, it should be available in localhost: 8081.  It's not likely but maybe another process already uses this port?

Can you send us the output of the following commands, might help us get a better picture:

`curl -I http://localhost:8081/health/is_alive`
`lsof -i :8081`
`docker ps`

**Comment by 94ri3** [comment]
I set those two parameters (BACKEND_PUBLIC_URL and BACKEND_INTERNAL_URL) and now it is working just fine.
thanks for your quick answer.

**Comment by frolovv** [comment]
closing the issue, tnx to all!

**Comment by kbill4345** [comment]
> I set those two parameters (BACKEND_PUBLIC_URL and BACKEND_INTERNAL_URL) and now it is working just fine.
> thanks for your quick answer.

hello ,i have the same problem
how to set this two parameters(BACKEND_PUBLIC_URL and BACKEND_INTERNAL_URL) ?

BACKEND_INTERNAL_URL=http://localhost:8081
BACKEND_PUBLIC_URL=http://localhost:8081

**Comment by sthuck** [comment]
@kbill4345 
Those parameters are really more intended for custom deployments of quix. Assuming you are just checking out quix using docker-compose like in our instructions [here](https://github.com/wix/quix#quick-start), you don't need to set those parameters, the default values should work fine.

If you are looking to run quix in some other customised way, the idea behind those parameters is simple. Quix is made up of two services, frontend, and backend. The frontend service also serves the client side code that runs in your browser. Both the client-side code and the frontend service need to reach the backend. `BACKEND_INTERNAL_URL` is how the frontend service should reach the backend,  `BACKEND_PUBLIC_URL` is how your browser should reach the backend. Most of the time, it will be the same value. For some rare deployment cases, those values might be different. 
![Quix architecture](https://user-images.githubusercontent.com/2864459/69904618-1f179600-13b1-11ea-916e-7afbc5f5d334.png)

If you still can't get Quix to run, let's open a new issue, so we won't send unnecessary notifications to people who had their issue resolved 😄. Describe how you are running quix (docker-compose or something else?), and I'll be glad to help.

**Comment by kbill4345** [comment]
thanks for your quick answer. I will open a new issuse
