### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by aweisberg** [wix/quix#127]
I tried to do a "docker-compose up" on [7eefbe3bfd598743d963c0e7b3d739d9f003ef17](https://github.com/wix/quix/commit/7eefbe3bfd598743d963c0e7b3d739d9f003ef17) and it doesn't seem to be working.

I removed all containers and images before testing this.

```
WARNING: The DB_VOLUME_PATH variable is not set. Defaulting to a blank string.
```

```
Successfully tagged quix_frontend:latest
WARNING: Image for service frontend was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating quix_presto_1 ... 
Creating quix_db_1     ... error

Creating quix_presto_1 ... done
h: '.' mount path must be absolute
Creating quix_backend_1 ... done

ERROR: for db  Cannot create container for service db: invalid volume specification: 'quix_db_volume:.:rw': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
```

**Comment by frolovv** [comment]
tnx for notifying us!

@sthuck can you look into it please?

**Comment by antonpod** [comment]
@aweisberg please create an `.env` file in the root folder with the following  configuration:
```
PRESTO_API=http://<your internal ip>:8085/v1
DB_VOLUME_PATH=/var/lib/mysql
AUTH_TYPE=fake
DB_NAME=quix
```

Please replace `<your internal ip>` with an actual IP or use `host.docker.internal` if you're on MAC.

**Comment by aweisberg** [comment]
Thanks! It worked.

I was confused a bit by [250fa3bd2f5e7071f96bcf01112f2e8e955b6cfb](https://github.com/wix/quix/commit/250fa3bd2f5e7071f96bcf01112f2e8e955b6cfb) which made it look like env-example was going to be used instead.

**Comment by sthuck** [comment]
@aweisberg my fault, sorry about that, indeed that was the intention of the commit but I misunderstood `docker-compose` documentation, and using a dedicated env-file didn't achieve the result I was looking for.
