### ISSUE TITLE
installation missing step

### ISSUE THREAD

**Issue by hedb** [wix/quix#181]
trying to install
passed the prerequisite
running docker-compose up
getting: 
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

i guess there is a missing step of cloning / downloading the repo

yours
impatient user

**Comment by sthuck** [comment]
Hello impatient yet important user,

you need a `.env` file, you can start by renaming our example file https://github.com/wix/quix/blob/master/env-example

**Comment by hedb** [comment]
yeap
figured that 
it was more of a documentation nitpicking and a _Hi there_ waving
