### ISSUE TITLE
DB Explorer not available after installation

### ISSUE THREAD

**Issue by hedb** [wix/quix#182]
<img width="1669" alt="Screen Shot 2019-11-06 at 7 48 54" src="https://user-images.githubusercontent.com/812947/68271754-49a05880-006a-11ea-9dcb-ead591109d91.png">

from the logs:

frontend_1  | [HPM] Error occurred while trying to proxy request /api/db/presto/explore from localhost:3000 to http:// (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by antonpod** [comment]
The backend might not have started yet, can you try again now?

**Comment by frolovv** [comment]
@hedb is this still happening? 

if yes, let's move the discussion to https://wix-quix.slack.com/archives/CQDAHT5UK

closing this issues meanwhile
