### ISSUE TITLE
Downloaded csv does not have column headers

### ISSUE THREAD

**Issue by bkowshik-rapido** [wix/quix#199]
*NOTE: I am new to exploring and working with Quix.*

### Steps
1. I run a query in the query which brings me results in the window below
2. Now, I click the `Download` icon to download the results as a `csv`
3. I am expecting this `csv` to have column headers, but it does not

### Questions
- What could be happening here
- Is this some configuration that needs to unset, etc

**Comment by antonpod** [comment]
@bkowshik-rapido thanks for reporting!

This was already fixed in f3c5472d5ef83bf5af3eac3168462a3ba6394ab1.
Please try to [build](https://wix.github.io/quix/docs/installation) from the master branch.

**Comment by bkowshik-rapido** [comment]
Awesome! Thank you @antonpod Closing here.
