### ISSUE TITLE
when creating a new notebook it is created with a new presto note which can't be deleted

### ISSUE THREAD

**Issue by hedb** [wix/quix#216]
1. We dont have a presto installed
when we create a note the only type we have is BQ

2. this is the console:
Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info. app.bundle.js:32079:21
window.controllers/Controllers is deprecated. Do not use it for UA detection. app.bundle.js:39626
The Notification permission may only be requested in a secure context. quix.cyco.fun:3000
Requesting Notification permission outside a short running user-generated event handler is deprecated and will not be supported in the future. quix.cyco.fun:3000
TypeError: "scope.vm is undefined"
    conf http://quix.cyco.fun:3000/app.bundle.js:135900
    withOptions http://quix.cyco.fun:3000/app.bundle.js:110682
    $digest http://quix.cyco.fun:3000/app.bundle.js:86812
    safeDigest http://quix.cyco.fun:3000/app.bundle.js:28105
    subscribe http://quix.cyco.fun:3000/app.bundle.js:124964
    controller http://quix.cyco.fun:3000/app.bundle.js:171155
    step http://quix.cyco.fun:3000/app.bundle.js:171113
    verb http://quix.cyco.fun:3000/app.bundle.js:171094
    fulfilled http://quix.cyco.fun:3000/app.bundle.js:171085
app.bundle.js:83239:41
TypeError: plugin is undefined
app.bundle.js:135909:29
TypeError: "scope.vm is undefined"
    conf http://quix.cyco.fun:3000/app.bundle.js:135900
    withOptions http://quix.cyco.fun:3000/app.bundle.js:110682
    $digest http://quix.cyco.fun:3000/app.bundle.js:86812
    $apply http://quix.cyco.fun:3000/app.bundle.js:87172
    onBlur http://quix.cyco.fun:3000/app.bundle.js:28126
    dispatch http://quix.cyco.fun:3000/app.bundle.js:22502
    handle http://quix.cyco.fun:3000/app.bundle.js:22309
app.bundle.js:83239:41
TypeError: plugin is undefined
app.bundle.js:135909:29
TypeError: "scope.vm is undefined"
    conf http://quix.cyco.fun:3000/app.bundle.js:135900
    withOptions http://quix.cyco.fun:3000/app.bundle.js:110682
    $digest http://quix.cyco.fun:3000/app.bundle.js:86812
    safeDigest http://quix.cyco.fun:3000/app.bundle.js:28105
    subscribe http://quix.cyco.fun:3000/app.bundle.js:124964
    controller http://quix.cyco.fun:3000/app.bundle.js:171155
    step http://quix.cyco.fun:3000/app.bundle.js:171113
    verb http://quix.cyco.fun:3000/app.bundle.js:171094
    fulfilled http://quix.cyco.fun:3000/app.bundle.js:171085
app.bundle.js:83239:41
TypeError: plugin is undefined
app.bundle.js:135909:29
Source map error: Error: request failed with status 404
Resource URL: http://quix.cyco.fun:3000/app.bundle.js
Source Map URL: actions.js.map

**Comment by antonpod** [comment]
Hi @hedb, are you building form master? (this issue should be resolved there)
