### ISSUE TITLE
Date type parameter is missing for BQ usage

### ISSUE THREAD

**Issue by hedb** [wix/quix#217]

**Comment by antonpod** [comment]
Hi @hedb , thanks for reporting.

Can you provide more details?

**Comment by hedb** [comment]
<img width="1086" alt="Screen Shot 2020-01-16 at 18 39 58" src="https://user-images.githubusercontent.com/812947/72544490-270f9480-3890-11ea-9fce-18e3e95fc890.png">

**Comment by frolovv** [comment]
@antonpod  bigquery timestamp and datetime datatypes must include seconds.

try running the following : 
```sql
-- works
SELECT TIMESTAMP '2020-01-17 02:03:04' as ts;

-- fails 
SELECT TIMESTAMP '2020-01-17 02:03' as ts
```
