### ISSUE TITLE
query works in BQ but not through Quix

### ISSUE THREAD

**Issue by hedb** [wix/quix#227]
CREATE TEMP FUNCTION jsonObjectKeys(input STRING)
RETURNS Array<String>
LANGUAGE js AS """
  return Object.keys(JSON.parse(input));
"""
;

select     
    jsonObjectKeys ( '{"a":1,"b":2}'  ) AS ports
    from temp.hed_test

**Comment by frolovv** [comment]
merged a fix that should add support to bigquery functions : 

![image](https://user-images.githubusercontent.com/2934915/74908702-43d34680-53bf-11ea-9ace-059ef2b36127.png)
