### ISSUE TITLE
Unable to delete the previously created erronous notes

### ISSUE THREAD

**Issue by hedb** [wix/quix#235]
Getting this: 
<img width="1667" alt="Screen Shot 2020-03-06 at 13 54 19" src="https://user-images.githubusercontent.com/812947/76082295-b47b8500-5fb3-11ea-8591-61f3943936e9.png">

when entering an old notebook that was created with the non-existing Presto plugin(and the note still can't be deleted)Not a real bug because i can just recreate notebooks but i have some large notebooks
Is there a way to delete these notes from the DB?

**Comment by antonpod** [comment]
@hedb please build from master
