### ISSUE TITLE
How do I change session user when connecting to Presto? 

### ISSUE THREAD

**Issue by zzztimbo** [wix/quix#250]
I'm trying to drop a Hive table in Presto and I'm getting this error. 

```
Access Denied: Cannot drop table gcs_export.foo: Owner of the table ('root') is different from session user ('dummy-user')
```

How do I change the name of my session user. I'm using 

```
AUTH_TYPE=fake
```

**Comment by frolovv** [comment]
hi @zzztimbo 

current presto implementation doesn't allow changing user on the fly, there is an open issue and PR related to it : https://github.com/prestosql/presto/issues/2308


regarding quix and presto auth : 
when you are using `AUTH_TYPE=fake` to run quix, we execute all queries from quix on behalf of `dummy-user`

we can add `AUTH_USER=desired-user-id` to control the user when `AUTH_TYPE=fake` is used

**Comment by frolovv** [comment]
@zzztimbo please pull the latest docker image of quix. 

now you can add `AUTH_USER=your-own-user` to the .env file and control the user that is used with presto.

it will work only if `AUTH_TYPE=fake` is present in config as well
