### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by nevetS** [wix/quix#255]
I'm not quite understanding from the documentation how users are managed in a multi-user environment.

Are the same database credentials used by all users?

It seems like the way it works is that you configure a set of database credentials on the server and those are used by all users when they sign in via google oauth.

If you want two groups of users with different permissions does that mean two different instances of quix?

How do you prevent unwanted users from gaining access?  For instance, if I wanted to deploy this for use within an engineering team, but didn't want the marketing team to be able to create accounts and log in?

It seems like I need to put this behind another layer of authorization.  (first company level auth, then if the users get past that, they google auth)

**Comment by antonpodolsky** [comment]
Hi @nevetS ,

At the moment Quix doesn't have a permissions layer. Any permissions should be defined on the DB level.

cc @frolovv @sthuck
