### ISSUE TITLE
Can't build the front end

### ISSUE THREAD

**Issue by Randgalt** [wix/quix#268]
I tried building/running quix-frontend/client via:

```shell
npm install
npm start
```

I get these errors (note, lodash appears to be installed)

```shell
../shared/entities/common/actions.ts:1:25 - error TS7016: Could not find a declaration file for module 'lodash'. '/xxx/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

1 import {mapValues} from 'lodash';
                          ~~~~~~~~

../shared/utils/utils.ts:1:25 - error TS7016: Could not find a declaration file for module 'lodash'. '/xxx/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

1 import {findIndex} from 'lodash';
                          ~~~~~~~~

../shared/entities/file/reducer.ts:1:28 - error TS7016: Could not find a declaration file for module 'lodash'. '/xxx/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

1 import {last, remove} from 'lodash';
 ```

Installing the types didn't help

**Comment by sthuck** [comment]
Hi @Randgalt ,

please run `npm install` in `quix-frontend/shared` folder as well, then you should be able to run `npm start` in the client folder. Please keep in mind that running `npm start` from the client folder will run only the client against a fake server, and is meant mainly for developing the UI.

**Comment by Randgalt** [comment]
Hi I build shared as well. Also, FYI, building the docker images fails with similar errors. Others have had this problem too.

**Comment by sthuck** [comment]
hi again @Randgalt,

sorry for the delay in handling this,  can you please re-try to build the client with docker/locally after removing `node_modules`? should work now.  let me know how it goes

**Comment by Randgalt** [comment]
Some other folks in our group got past it. Maybe they can describe what they did. cc @lukasz-walkiewicz && @huberty89

**Comment by lukasz-walkiewicz** [comment]
I think the problem here is that `package-lock.json` files are missing because they're intentionally untracked though `.gitignore`. This produces different build results due to changing npm dependencies versions depending on the local version of `package-lock.json` or time of the build. I've managed to fix it by extracting the lock files from the latest official docker image.
