### ISSUE TITLE
Cant build the front end in windows -Need help 

### ISSUE THREAD

**Issue by TarunTeja333** [wix/quix#271]
Hi , I'm very new to these projects . I am using windows machine .
There is a closed issue for running in windows . https://github.com/wix/quix/issues/197
* Do we need to install docker ?
 I have tried the same command in Windows cmd "pm2 start ecosystem.config.js" . I'm unable to make the front-end run .
image

No output on the browser at http://localhost:3000/
output : C:\Users\user\Desktop\ProjectNewCastle\quix\quix\quix-frontend\service>pm2 start ecosystem.config.js
[PM2] Applying action restartProcessId on app [quix](ids: [ 0, 1 ])
[PM2] quix ✓
[PM2] quix ✓
┌─────┬─────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name │ namespace │ version │ mode │ pid │ uptime │ ↺ │ status │ cpu │ mem │ user │ watching │
├─────┼─────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0 │ quix │ default │ 0.0.1 │ cluster │ 4968 │ 0s │ 82 │ online │ 0% │ 0b │ user │ disabled │
│ 1 │ quix │ default │ 0.0.1 │ cluster │ 4640 │ 0s │ 80 │ online │ 0% │ 31.2mb │ user │ disabled │
└─────┴─────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

Updated application.properties in "quix\quix\quix-backend\quix-webapps\quix-web-spring\src\main\resources\application.properties"
*Unable to find env.properties as mentioned above :
Can anyone please help me run this in windows .
Any suggestion is appreciated , Thanks

**Comment by sthuck** [comment]
hi @TarunTeja333 ,

I don't have access to a windows machine for now, I will try to help and see how far we get.

First I need to understand better what you are trying to achieve - 
If all you want is to run quix locally - docker is the simplest way to do so. I highly recommend it.

running quix locally without docker is much more complex and not as documented, it's mostly useful if you want to develop code and modify quix, as you need to build and run all components yourself.

if that's your intention, we can move forward in that direction and try to get you running. At first stage, please remember quix has 2 components, a node.js frontend, and a scala backend, both need to be running. You also need a mysql db to store notebook (can be in-mem sqlite if you set environment variable `DB_TYPE=sqlite`) and some data source.
