### ISSUE TITLE
Connection Lost Issue

### ISSUE THREAD

**Issue by suhasadhav** [wix/quix#292]
Hi,
I have created local instance using docker but somehow I am getting error Connection Lost without any clue:
Below is my .env file:
```
#MODULES=presto,athena,prod,bq
MODULES=presto

MODULES_PRESTO_ENGINE=presto
MODULES_PRESTO_API=http://presto:8080/v1
MODULES_PRESTO_CATALOG=system
MODULES_PRESTO_SCHEMA=runtime
MODULES_PRESTO_SOURCE=quix
MODULES_PRESTO_DB_EMPTY_TIMEOUT=6000000
MODULES_PRESTO_DB_REQUEST_TIMEOUT=1000000

#MODULES_ATHENA_ENGINE=athena
#MODULES_ATHENA_OUTPUT=s3://some-bucket-id/
#MODULES_ATHENA_REGION=us-east-1
#MODULES_ATHENA_DATABASE=default
#MODULES_ATHENA_DB_EMPTY_TIMEOUT=60000
#MODULES_ATHENA_DB_REQUEST_TIMEOUT=10000

#MODULES_PROD_ENGINE=jdbc
#MODULES_PROD_DRIVER=com.mysql.jdbc.Driver
#MODULES_PROD_URL=jdbc:mysql://localhost:2222/aschema
#MODULES_PROD_USER=prod-user
#MODULES_PROD_PASS=prod-pass
#MODULES_PROD_SYNTAX=mysql

#MODULES_BQ_ENGINE=bigquery
#MODULES_BQ_SYNTAX=ansi_sql
#MODULES_BQ_CREDENTIALS_BASE64= BASE64 of credentials.json

#fake or google
AUTH_TYPE=fake
AUTH_USER=dummy-user
AUTH_COOKIE=
AUTH_SECRET=
DB_NAME=quix
DB_USER=
DB_PASS=
DB_HOST=
DB_PORT=
BACKEND_INTERNAL_URL=http://backend:8081
BACKEND_PUBLIC_URL=http://backend:8081
GOOGLE_SSO_CLIENT_ID=
GOOGLE_SSO_SECRET=
```

Below is the error:
![image](https://user-images.githubusercontent.com/9277450/111430036-cee85280-871f-11eb-8be8-e35b86bb3e75.png)

I have tried to set **BACKEND_INTERNAL_URL and BACKEND_PUBLIC_URL** as given in .env file above but still same issue persists.

Log files attached for all containers.
[frontend.txt](https://github.com/wix/quix/files/6154445/frontend.txt)
[mysql.log.txt](https://github.com/wix/quix/files/6154446/mysql.log.txt)
[presto.txt](https://github.com/wix/quix/files/6154447/presto.txt)
[backend.txt](https://github.com/wix/quix/files/6154448/backend.txt)

**Comment by suhasadhav** [comment]
Could anyone please help here?

We tried to debug this by calling presto api, this is what we got:
![image](https://user-images.githubusercontent.com/9277450/112430090-abe32180-8d63-11eb-9936-c875483cfd90.png)

**Comment by frolovv** [comment]
@suhasadhav please change the 

`BACKEND_PUBLIC_URL=http://backend:8081`

to `BACKEND_PUBLIC_URL=http://localhost:8081`

what happens is that the above piece of config gets to your browser and the browser can't resolve hostname called `backend`

**Comment by suhasadhav** [comment]
Thanks for the help, it worked after changing BACKEND_PUBLIC_URL.
