### ISSUE TITLE
using latest trinodb/trino image leads to connection error

### ISSUE THREAD

**Issue by Ognian** [wix/quix#293]
when replacing the presto image with the latest trinodb/trino image (354) the backend gets the following error:
```
2021-04-02 14:54:54,416 INFO  [scala-execution-context-global-39] quix.presto.rest.ScalaJPrestoStateClient : method=init query-id=76d1815f-6c54-4c9d-9301-dfeae5eb2ef8 query-sql=[show catalogs
2021-04-02 14:54:54,423 ERROR [scala-execution-context-global-39]                 quix.core.utils.TaskOps$ : event=read-presto-state-error response.code=401 response.body=Basic authentication or X-Trino-User must be sent
```
Any Ideas?
Ognian

**Comment by Ognian** [comment]
Looks like they changed all the headers from X-Presto* to X-Trino* and they are hard coded [here](https://github.com/wix/quix/blob/409cc63c748ff4a021127136ee454fb0ad50da18/quix-backend/quix-modules/quix-presto-module/src/main/scala/quix/presto/rest/ScalaJPrestoOps.scala#L19)

**Comment by Ognian** [comment]
Ups Sorry, as per https://trino.io/docs/current/admin/properties-general.html
it looks like there is a `protocol.v1.alternate-header-name` which can be set to `Presto` will test and report back...

**Comment by Ognian** [comment]
yes this works, so sorry for the noise;
I'll let this issue open since the setting is actually deprecated and you should decide the best way how you'll like to support it...

**Comment by frolovv** [comment]
tnx for reporting @Ognian !

we will handle it (probably via config toggle)

**Comment by frolovv** [comment]
there is a new config param called `HTTP_HEADERS_PREFIX` for presto/trino modules

it allows you to specify the desired prefix, use `X-PRESTO-` for presto or `X-TRINO-` for trino respectively. 

here is .env file and presto example : 
https://github.com/wix/quix/blob/20abcb75a5912fefc412ffe9bc900d87e2b9f540/env-example#L12
