### ISSUE TITLE
Frontend Client Bundle Size Improvement

### ISSUE THREAD

**Issue by hanipcode** [wix/quix#317]
Hi, @frolovv @antonpodolsky 
I noticed that in the frontend bundle quix are simply build using typescript, resulting in a huge bundle size. is there any specific reason to use this ?
if not, what do you think about bundling using webpack ? I can work on the PR too.
I was going to use quix but the resulting frontend bundle is like 9MB. thinking to fork and modify the bundler for myself but noticing that quix is actively updated.

**Comment by antonpodolsky** [comment]
Hi, it's actually Webpack under the hood.

**Comment by hanipcode** [comment]
Hmm when I check in the demo site it bundles to around 5-6MB, but when I tried to run it it resulting in 9MB bundle size. am I using dev build / something ? I just run docker compose up like in the installation section.
by the way what is the expected optimized bundle size ?

**Comment by antonpodolsky** [comment]
Our internal deployment is around 3 MB during initial load, 1 MB of which is the plotting library we use.
Will try to see why local docker results in a bigger bundle.

**Comment by antonpodolsky** [comment]
Down to 2.1 Mb total, we were indeed running in debug mode by mistake, thanks for bringing this to our attention.

**Comment by hanipcode** [comment]
sure, I will wait the fix and try to reinstall. I'm ready to help too if needed 👍

**Comment by antonpodolsky** [comment]
The change was merged, you can try it.

**Comment by frolovv** [comment]
seems like the issue was resolved, closing
