### ISSUE TITLE
Question: Can you join across DBs within Quix?

### ISSUE THREAD

**Issue by ds-noahdolev** [wix/quix#325]
If we import two DBs via JDBC, can we join between tables in the different DBs in a single note?

If not, can we create table to a third location? 

For example:

```{SQL}
CREATE TABLE db1.new_table AS 
(
SELECT * FROM db2.table WHERE db2.table.field = 1
)
```

**Comment by frolovv** [comment]
not really, you have to use some external system such as [presto](https://prestodb.io/) or [trino](https://trino.io/)

**Comment by ds-noahdolev** [comment]
Thanks! :)
