### ISSUE TITLE
featuring Quix in Docusaurus

### ISSUE THREAD

**Issue by nickbui729** [wix/quix#77]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) 

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by antonpod** [comment]
Hi, we'll be glad to be featured, you can find the logo here http://quix.sthuck.info:3000/assets/logo_big.png

**Comment by antonpod** [comment]
Please link it to https://wix.github.io/quix/

**Comment by nickbui729** [comment]
Awesome to here! Thank you.

**Comment by sthuck** [comment]
thanks @nickbui729 😄
