### ISSUE TITLE
[Question] clickhouse support

### ISSUE THREAD

**Issue by vbichov** [wix/quix#95]
do you guys have docs on how to add additional data sources?

It would be great if you supported other datasources (similar to:
https://redash.io/help/data-sources/setup/supported-data-sources
)

I'm currently interested in: https://clickhouse.yandex/
Do you have plans to support it (and similar)?

Thanks

**Comment by frolovv** [comment]
we plan adding support for jdbc-based data sources in the future

i see that clickhouse has 2 jdbc drivers.

**Comment by frolovv** [comment]
@vbichov we added support for custom jdbc drivers to quix.

you can update the .env file with : 
```
MODULES=clickhouse

MODULES_CLICKHOUSE_ENGINE=jdbc
MODULES_CLICKHOUSE_DRIVER=ru.yandex.clickhouse.ClickHouseDriver
MODULES_CLICKHOUSE_URL=jdbc:clickhouse://<host:port>
MODULES_CLICKHOUSE_USER=<user>
MODULES_CLICKHOUSE_PASS=<pass>
MODULES_CLICKHOUSE_SYNTAX=ansi_sql
```

and `docker-compose up`

you will see a new note type called 'clickhouse' and will be able to query the tables
